/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as IncidentesIndexRouteImport } from './routes/incidentes.index'
import { Route as IncidentesNovoRouteImport } from './routes/incidentes.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentesIndexRoute = IncidentesIndexRouteImport.update({
  id: '/incidentes/',
  path: '/incidentes/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentesNovoRoute = IncidentesNovoRouteImport.update({
  id: '/incidentes/novo',
  path: '/incidentes/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRoute
  '/incidentes/novo': typeof IncidentesNovoRoute
  '/incidentes/': typeof IncidentesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel': typeof PainelRoute
  '/incidentes/novo': typeof IncidentesNovoRoute
  '/incidentes': typeof IncidentesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRoute
  '/incidentes/novo': typeof IncidentesNovoRoute
  '/incidentes/': typeof IncidentesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/painel' | '/incidentes/novo' | '/incidentes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/painel' | '/incidentes/novo' | '/incidentes'
  id: '__root__' | '/' | '/painel' | '/incidentes/novo' | '/incidentes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRoute: typeof PainelRoute
  IncidentesNovoRoute: typeof IncidentesNovoRoute
  IncidentesIndexRoute: typeof IncidentesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidentes/': {
      id: '/incidentes/'
      path: '/incidentes'
      fullPath: '/incidentes/'
      preLoaderRoute: typeof IncidentesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidentes/novo': {
      id: '/incidentes/novo'
      path: '/incidentes/novo'
      fullPath: '/incidentes/novo'
      preLoaderRoute: typeof IncidentesNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRoute: PainelRoute,
  IncidentesNovoRoute: IncidentesNovoRoute,
  IncidentesIndexRoute: IncidentesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
